-- MySQL Script generated by MySQL Workbench
-- Sun Jul  5 01:01:15 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FitnessProject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FitnessProject` ;

-- -----------------------------------------------------
-- Schema FitnessProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FitnessProject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `FitnessProject` ;

-- -----------------------------------------------------
-- Table `FitnessProject`.`EmailOTP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`EmailOTP` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`EmailOTP` (
  `id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `otp_code` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `purpose` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `expired_at` DATETIME(6) NOT NULL,
  `is_used` TINYINT(1) NOT NULL,
  `attempt_count` INT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IX_EmailOTP_Email` (`email` ASC) VISIBLE,
  INDEX `IX_EmailOTP_ExpiredAt` (`expired_at` ASC) VISIBLE,
  INDEX `IX_EmailOTP_Purpose` (`purpose` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`__EFMigrationsHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`__EFMigrationsHistory` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`__EFMigrationsHistory` (
  `migration_id` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `product_version` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`migration_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`roles` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`users` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password_hash` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `google_id` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `avatar_url` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `gender` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `date_of_birth` DATETIME(6) NULL DEFAULT NULL,
  `status` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `fitness_goal` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `password_changed_at` DATETIME(6) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_users_role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `FitnessProject`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`ai_recommendations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`ai_recommendations` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`ai_recommendations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `type` INT NOT NULL,
  `user_request` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `ai_response` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_ai_recommendations_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_ai_recommendations_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`body_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`body_metrics` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`body_metrics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `height` DECIMAL(65,30) NULL DEFAULT NULL,
  `weight` DECIMAL(65,30) NOT NULL,
  `body_fat_percentage` DECIMAL(65,30) NULL DEFAULT NULL,
  `muscle_mass` DECIMAL(65,30) NULL DEFAULT NULL,
  `bmi` DECIMAL(65,30) NULL DEFAULT NULL,
  `recorded_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_body_metrics_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_body_metrics_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`daily_nutrition_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`daily_nutrition_logs` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`daily_nutrition_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `log_date` DATETIME(6) NOT NULL,
  `calories_target` INT NOT NULL,
  `protein_target_grams` DECIMAL(65,30) NOT NULL,
  `carbs_target_grams` DECIMAL(65,30) NOT NULL,
  `fat_target_grams` DECIMAL(65,30) NOT NULL,
  `water_target_glasses` INT NOT NULL,
  `calories_consumed` INT NOT NULL,
  `protein_consumed_grams` DECIMAL(65,30) NOT NULL,
  `carbs_consumed_grams` DECIMAL(65,30) NOT NULL,
  `fat_consumed_grams` DECIMAL(65,30) NOT NULL,
  `water_consumed_glasses` INT NOT NULL,
  `calories_burned` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IX_DailyNutritionLog_UserId_LogDate` (`user_id` ASC, `log_date` ASC) VISIBLE,
  CONSTRAINT `fk_daily_nutrition_logs_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`muscle_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`muscle_groups` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`muscle_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`exercises` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `video_url` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `muscle_group` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `difficulty` INT NOT NULL,
  `duration` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `creator_id` INT NULL DEFAULT NULL,
  `muscle_group_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_exercises_creator_id` (`creator_id` ASC) VISIBLE,
  INDEX `ix_exercises_muscle_group_id` (`muscle_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercises_muscle_groups_muscle_group_id`
    FOREIGN KEY (`muscle_group_id`)
    REFERENCES `FitnessProject`.`muscle_groups` (`id`),
  CONSTRAINT `fk_exercises_users_creator_id`
    FOREIGN KEY (`creator_id`)
    REFERENCES `FitnessProject`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`foods` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`foods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `serving_size` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `unit` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `calories` INT NOT NULL,
  `protein` DECIMAL(65,30) NOT NULL,
  `carbs` DECIMAL(65,30) NOT NULL,
  `fat` DECIMAL(65,30) NOT NULL,
  `image_url` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`meal_schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`meal_schedules` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`meal_schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `ai_recommendation_id` INT NULL DEFAULT NULL,
  `schedule_name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `eat_time` TIME NULL DEFAULT NULL,
  `total_calories_target` INT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_meal_schedules_ai_recommendation_id` (`ai_recommendation_id` ASC) VISIBLE,
  INDEX `ix_meal_schedules_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_meal_schedules_ai_recommendations_ai_recommendation_id`
    FOREIGN KEY (`ai_recommendation_id`)
    REFERENCES `FitnessProject`.`ai_recommendations` (`id`),
  CONSTRAINT `fk_meal_schedules_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`meal_schedule_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`meal_schedule_items` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`meal_schedule_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meal_schedule_id` INT NOT NULL,
  `food_id` INT NOT NULL,
  `amount` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `is_eaten` TINYINT(1) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_meal_schedule_items_food_id` (`food_id` ASC) VISIBLE,
  INDEX `ix_meal_schedule_items_meal_schedule_id` (`meal_schedule_id` ASC) VISIBLE,
  CONSTRAINT `fk_meal_schedule_items_foods_food_id`
    FOREIGN KEY (`food_id`)
    REFERENCES `FitnessProject`.`foods` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_meal_schedule_items_meal_schedules_meal_schedule_id`
    FOREIGN KEY (`meal_schedule_id`)
    REFERENCES `FitnessProject`.`meal_schedules` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`product_packages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`product_packages` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`product_packages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `type` INT NOT NULL,
  `price` DECIMAL(65,30) NOT NULL,
  `duration_days` INT NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `is_popular` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`orders` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `package_id` INT NULL DEFAULT NULL,
  `price_paid` DECIMAL(65,30) NOT NULL,
  `payment_status` INT NOT NULL,
  `purchased_at` DATETIME(6) NOT NULL,
  `expired_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_orders_package_id` (`package_id` ASC) VISIBLE,
  INDEX `ix_orders_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_product_packages_package_id`
    FOREIGN KEY (`package_id`)
    REFERENCES `FitnessProject`.`product_packages` (`id`),
  CONSTRAINT `fk_orders_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`membership_subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`membership_subscriptions` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`membership_subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `package_id` INT NOT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `start_date` DATETIME(6) NOT NULL,
  `end_date` DATETIME(6) NOT NULL,
  `status` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_membership_subscriptions_order_id` (`order_id` ASC) VISIBLE,
  INDEX `ix_membership_subscriptions_package_id` (`package_id` ASC) VISIBLE,
  INDEX `ix_membership_subscriptions_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_membership_subscriptions_orders_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `FitnessProject`.`orders` (`id`),
  CONSTRAINT `fk_membership_subscriptions_product_packages_package_id`
    FOREIGN KEY (`package_id`)
    REFERENCES `FitnessProject`.`product_packages` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_membership_subscriptions_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`notifications` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `content` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `type` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_read` TINYINT(1) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_notifications_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notifications_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`payments` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `payment_method` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `transaction_code` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `amount` DECIMAL(65,30) NOT NULL,
  `status` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `paid_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_payments_order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_orders_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `FitnessProject`.`orders` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`pt_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`pt_profiles` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`pt_profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `bio` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `experience_years` INT NULL DEFAULT NULL,
  `rating` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ix_pt_profiles_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_pt_profiles_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`pt_upload_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`pt_upload_requests` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`pt_upload_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pt_id` INT NOT NULL,
  `exercise_id` INT NULL DEFAULT NULL,
  `title` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `video_url` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `status` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `admin_id` INT NULL DEFAULT NULL,
  `review_note` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `submitted_at` DATETIME(6) NULL DEFAULT NULL,
  `reviewed_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_pt_upload_requests_admin_id` (`admin_id` ASC) VISIBLE,
  INDEX `ix_pt_upload_requests_exercise_id` (`exercise_id` ASC) VISIBLE,
  INDEX `ix_pt_upload_requests_pt_id` (`pt_id` ASC) VISIBLE,
  CONSTRAINT `fk_pt_upload_requests_exercises_exercise_id`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `FitnessProject`.`exercises` (`id`),
  CONSTRAINT `fk_pt_upload_requests_users_admin_id`
    FOREIGN KEY (`admin_id`)
    REFERENCES `FitnessProject`.`users` (`id`),
  CONSTRAINT `fk_pt_upload_requests_users_pt_id`
    FOREIGN KEY (`pt_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`schedules` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pt_id` INT NULL DEFAULT NULL,
  `member_id` INT NULL DEFAULT NULL,
  `start_time` DATETIME(6) NOT NULL,
  `end_time` DATETIME(6) NOT NULL,
  `status` INT NOT NULL,
  `meeting_url` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_schedules_member_id` (`member_id` ASC) VISIBLE,
  INDEX `ix_schedules_pt_id` (`pt_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedules_users_member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_schedules_users_pt_id`
    FOREIGN KEY (`pt_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`workout_plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`workout_plans` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`workout_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `ai_recommendation_id` INT NULL DEFAULT NULL,
  `title` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `goal` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `target_calories` INT NULL DEFAULT NULL,
  `target_duration_minutes` INT NULL DEFAULT NULL,
  `created_by_ai` TINYINT(1) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_workout_plans_ai_recommendation_id` (`ai_recommendation_id` ASC) VISIBLE,
  INDEX `ix_workout_plans_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_workout_plans_ai_recommendations_ai_recommendation_id`
    FOREIGN KEY (`ai_recommendation_id`)
    REFERENCES `FitnessProject`.`ai_recommendations` (`id`),
  CONSTRAINT `fk_workout_plans_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`workout_plan_exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`workout_plan_exercises` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`workout_plan_exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_plan_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `sets` INT NULL DEFAULT NULL,
  `reps` INT NULL DEFAULT NULL,
  `duration_seconds` INT NULL DEFAULT NULL,
  `rest_seconds` INT NULL DEFAULT NULL,
  `exercise_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_workout_plan_exercises_exercise_id` (`exercise_id` ASC) VISIBLE,
  INDEX `ix_workout_plan_exercises_workout_plan_id` (`workout_plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_workout_plan_exercises_exercises_exercise_id`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `FitnessProject`.`exercises` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_workout_plan_exercises_workout_plans_workout_plan_id`
    FOREIGN KEY (`workout_plan_id`)
    REFERENCES `FitnessProject`.`workout_plans` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`workout_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`workout_sessions` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`workout_sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `workout_plan_id` INT NULL DEFAULT NULL,
  `total_duration_minutes` INT NULL DEFAULT NULL,
  `total_calories_burned` DECIMAL(65,30) NULL DEFAULT NULL,
  `status` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `started_at` DATETIME(6) NULL DEFAULT NULL,
  `completed_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_workout_sessions_user_id` (`user_id` ASC) VISIBLE,
  INDEX `ix_workout_sessions_workout_plan_id` (`workout_plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_workout_sessions_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_workout_sessions_workout_plans_workout_plan_id`
    FOREIGN KEY (`workout_plan_id`)
    REFERENCES `FitnessProject`.`workout_plans` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`workout_session_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`workout_session_details` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`workout_session_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_session_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `sets_done` INT NULL DEFAULT NULL,
  `reps_done` INT NULL DEFAULT NULL,
  `duration_seconds` INT NULL DEFAULT NULL,
  `calories_burned` DECIMAL(65,30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_workout_session_details_exercise_id` (`exercise_id` ASC) VISIBLE,
  INDEX `ix_workout_session_details_workout_session_id` (`workout_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_workout_session_details_exercises_exercise_id`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `FitnessProject`.`exercises` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_workout_session_details_workout_sessions_workout_session_id`
    FOREIGN KEY (`workout_session_id`)
    REFERENCES `FitnessProject`.`workout_sessions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `FitnessProject` ;

-- -----------------------------------------------------
-- procedure POMELO_AFTER_ADD_PRIMARY_KEY
-- -----------------------------------------------------

USE `FitnessProject`;
DROP procedure IF EXISTS `FitnessProject`.`POMELO_AFTER_ADD_PRIMARY_KEY`;

DELIMITER $$
USE `FitnessProject`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255), IN `COLUMN_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID INT(11);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
			AND `COLUMN_TYPE` LIKE '%int%'
			AND `COLUMN_KEY` = 'PRI';
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
				AND `COLUMN_TYPE` LIKE '%int%'
				AND `COLUMN_KEY` = 'PRI';
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
				AND `COLUMN_TYPE` LIKE '%int%'
				AND `COLUMN_KEY` = 'PRI';
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL AUTO_INCREMENT;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure POMELO_BEFORE_DROP_PRIMARY_KEY
-- -----------------------------------------------------

USE `FitnessProject`;
DROP procedure IF EXISTS `FitnessProject`.`POMELO_BEFORE_DROP_PRIMARY_KEY`;

DELIMITER $$
USE `FitnessProject`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID TINYINT(1);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `Extra` = 'auto_increment'
			AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
