-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 15:38:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET NAMES utf8mb4;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FitnessProject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FitnessProject` ;

-- -----------------------------------------------------
-- Schema FitnessProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FitnessProject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `FitnessProject` ;

-- -----------------------------------------------------
-- Table `FitnessProject`.`ai_recommendations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`ai_recommendations` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`ai_recommendations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `type` ENUM('WORKOUT_PLAN', 'NUTRITION_DIET') NOT NULL,
  `user_request` TEXT NULL DEFAULT NULL,
  `ai_response` LONGTEXT NOT NULL,
  `model_name` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `ai_recommendations_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`body_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`body_metrics` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`body_metrics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `height` DECIMAL(5,2) NULL DEFAULT NULL,
  `weight` DECIMAL(5,2) NOT NULL,
  `body_fat_percentage` DECIMAL(4,2) NULL DEFAULT NULL,
  `muscle_mass` DECIMAL(5,2) NULL DEFAULT NULL,
  `bmi` DECIMAL(5,2) NULL DEFAULT NULL,
  `recorded_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `body_metrics_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`exercises` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  `thumbnail_url` VARCHAR(255) NULL DEFAULT NULL,
  `muscle_group_id` INT NULL DEFAULT NULL,
  `difficulty` ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL,
  `equipment` VARCHAR(100) NULL DEFAULT 'No Equipment',
  `duration` INT NULL DEFAULT NULL,
  `calories_burn_per_min` DECIMAL(5,2) NULL DEFAULT '0.00',
  `created_by` INT NULL DEFAULT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NULL DEFAULT 'APPROVED',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `muscle_group_id` (`muscle_group_id` ASC) VISIBLE,
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `exercises_ibfk_1`
    FOREIGN KEY (`muscle_group_id`)
    REFERENCES `FitnessProject`.`muscle_groups` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `exercises_ibfk_2`
    FOREIGN KEY (`created_by`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`foods` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`foods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `serving_size` VARCHAR(50) NULL DEFAULT NULL,
  `unit` VARCHAR(30) NULL DEFAULT NULL,
  `calories` INT NOT NULL,
  `protein` DECIMAL(5,2) NULL DEFAULT '0.00',
  `carbs` DECIMAL(5,2) NULL DEFAULT '0.00',
  `fat` DECIMAL(5,2) NULL DEFAULT '0.00',
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`meal_schedule_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`meal_schedule_items` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`meal_schedule_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meal_schedule_id` INT NOT NULL,
  `food_id` INT NOT NULL,
  `amount` VARCHAR(50) NOT NULL,
  `is_eaten` TINYINT(1) NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `meal_schedule_id` (`meal_schedule_id` ASC) VISIBLE,
  INDEX `food_id` (`food_id` ASC) VISIBLE,
  CONSTRAINT `meal_schedule_items_ibfk_1`
    FOREIGN KEY (`meal_schedule_id`)
    REFERENCES `FitnessProject`.`meal_schedules` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `meal_schedule_items_ibfk_2`
    FOREIGN KEY (`food_id`)
    REFERENCES `FitnessProject`.`foods` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`meal_schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`meal_schedules` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`meal_schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `ai_recommendation_id` INT NULL DEFAULT NULL,
  `schedule_name` VARCHAR(100) NOT NULL,
  `eat_time` TIME NULL DEFAULT NULL,
  `total_calories_target` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `ai_recommendation_id` (`ai_recommendation_id` ASC) VISIBLE,
  CONSTRAINT `meal_schedules_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `meal_schedules_ibfk_2`
    FOREIGN KEY (`ai_recommendation_id`)
    REFERENCES `FitnessProject`.`ai_recommendations` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`membership_subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`membership_subscriptions` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`membership_subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `package_id` INT NOT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `status` ENUM('ACTIVE', 'EXPIRED', 'CANCELLED') NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `package_id` (`package_id` ASC) VISIBLE,
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `membership_subscriptions_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `membership_subscriptions_ibfk_2`
    FOREIGN KEY (`package_id`)
    REFERENCES `FitnessProject`.`product_packages` (`id`),
  CONSTRAINT `membership_subscriptions_ibfk_3`
    FOREIGN KEY (`order_id`)
    REFERENCES `FitnessProject`.`orders` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`muscle_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`muscle_groups` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`muscle_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`notifications` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `content` TEXT NOT NULL,
  `type` ENUM('SYSTEM', 'WORKOUT', 'SCHEDULE', 'PAYMENT', 'MEMBERSHIP') NULL DEFAULT 'SYSTEM',
  `is_read` TINYINT(1) NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `notifications_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`orders` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `package_id` INT NOT NULL,
  `price_paid` DECIMAL(10,2) NOT NULL,
  `payment_status` ENUM('PENDING', 'PAID', 'FAILED', 'CANCELLED') NULL DEFAULT 'PENDING',
  `purchased_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `package_id` (`package_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`package_id`)
    REFERENCES `FitnessProject`.`product_packages` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`payments` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `payment_method` ENUM('CASH', 'MOMO', 'VNPAY', 'PAYOS', 'BANK_TRANSFER') NOT NULL,
  `transaction_code` VARCHAR(100) NULL DEFAULT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `status` ENUM('PENDING', 'SUCCESS', 'FAILED') NULL DEFAULT 'PENDING',
  `paid_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `FitnessProject`.`orders` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`product_packages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`product_packages` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`product_packages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` ENUM('MEMBERSHIP', 'ONLINE_WORKOUT') NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `duration_days` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `is_popular` TINYINT(1) NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`pt_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`pt_profiles` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`pt_profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `bio` TEXT NULL DEFAULT NULL,
  `specialization` VARCHAR(150) NULL DEFAULT NULL,
  `experience_years` INT NULL DEFAULT '0',
  `certificate_url` VARCHAR(255) NULL DEFAULT NULL,
  `rating` DECIMAL(3,2) NULL DEFAULT '5.00',
  `hourly_rate` DECIMAL(10,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `pt_profiles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`pt_upload_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`pt_upload_requests` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`pt_upload_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pt_id` INT NOT NULL,
  `exercise_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(150) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `video_url` VARCHAR(255) NOT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NULL DEFAULT 'PENDING',
  `admin_id` INT NULL DEFAULT NULL,
  `review_note` TEXT NULL DEFAULT NULL,
  `submitted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `reviewed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pt_id` (`pt_id` ASC) VISIBLE,
  INDEX `exercise_id` (`exercise_id` ASC) VISIBLE,
  INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `pt_upload_requests_ibfk_1`
    FOREIGN KEY (`pt_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `pt_upload_requests_ibfk_2`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `FitnessProject`.`exercises` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `pt_upload_requests_ibfk_3`
    FOREIGN KEY (`admin_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`roles` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`schedules` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pt_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `status` ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED') NULL DEFAULT 'PENDING',
  `meeting_url` VARCHAR(512) NULL DEFAULT NULL,
  `note` TEXT NULL DEFAULT NULL,
  `cancel_reason` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `pt_id` (`pt_id` ASC) VISIBLE,
  INDEX `member_id` (`member_id` ASC) VISIBLE,
  CONSTRAINT `schedules_ibfk_1`
    FOREIGN KEY (`pt_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `schedules_ibfk_2`
    FOREIGN KEY (`member_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`users` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `google_id` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `avatar_url` VARCHAR(255) NULL DEFAULT NULL,
  `gender` ENUM('MALE', 'FEMALE', 'OTHER') NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE', 'BANNED') NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `password_changed_at` DATETIME NULL DEFAULT NULL,
  `fitness_goal` VARCHAR(50) NULL DEFAULT 'MAINTAIN',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `FitnessProject`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`workout_plan_exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`workout_plan_exercises` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`workout_plan_exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_plan_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `sets` INT NULL DEFAULT '1',
  `reps` INT NULL DEFAULT NULL,
  `duration_seconds` INT NULL DEFAULT NULL,
  `rest_seconds` INT NULL DEFAULT '60',
  `exercise_order` INT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `workout_plan_id` (`workout_plan_id` ASC) VISIBLE,
  INDEX `exercise_id` (`exercise_id` ASC) VISIBLE,
  CONSTRAINT `workout_plan_exercises_ibfk_1`
    FOREIGN KEY (`workout_plan_id`)
    REFERENCES `FitnessProject`.`workout_plans` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `workout_plan_exercises_ibfk_2`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `FitnessProject`.`exercises` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`workout_plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`workout_plans` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`workout_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `ai_recommendation_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(150) NOT NULL,
  `goal` VARCHAR(150) NULL DEFAULT NULL,
  `target_calories` INT NULL DEFAULT NULL,
  `target_duration_minutes` INT NULL DEFAULT NULL,
  `created_by_ai` TINYINT(1) NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `ai_recommendation_id` (`ai_recommendation_id` ASC) VISIBLE,
  CONSTRAINT `workout_plans_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `workout_plans_ibfk_2`
    FOREIGN KEY (`ai_recommendation_id`)
    REFERENCES `FitnessProject`.`ai_recommendations` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`workout_session_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`workout_session_details` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`workout_session_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_session_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `sets_done` INT NULL DEFAULT '0',
  `reps_done` INT NULL DEFAULT '0',
  `duration_seconds` INT NULL DEFAULT '0',
  `calories_burned` DECIMAL(8,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `workout_session_id` (`workout_session_id` ASC) VISIBLE,
  INDEX `exercise_id` (`exercise_id` ASC) VISIBLE,
  CONSTRAINT `workout_session_details_ibfk_1`
    FOREIGN KEY (`workout_session_id`)
    REFERENCES `FitnessProject`.`workout_sessions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `workout_session_details_ibfk_2`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `FitnessProject`.`exercises` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `FitnessProject`.`workout_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`workout_sessions` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`workout_sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `workout_plan_id` INT NULL DEFAULT NULL,
  `total_duration_minutes` INT NULL DEFAULT '0',
  `total_calories_burned` DECIMAL(8,2) NULL DEFAULT '0.00',
  `status` ENUM('IN_PROGRESS', 'COMPLETED', 'CANCELLED') NULL DEFAULT 'IN_PROGRESS',
  `started_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `workout_plan_id` (`workout_plan_id` ASC) VISIBLE,
  CONSTRAINT `workout_sessions_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `workout_sessions_ibfk_2`
    FOREIGN KEY (`workout_plan_id`)
    REFERENCES `FitnessProject`.`workout_plans` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ==========================================
-- BƯỚC 5: NẠP DỮ LIỆU NỀN
-- ==========================================
INSERT IGNORE INTO `FitnessProject`.`roles` (`id`, `role_name`) VALUES 
(1, 'ADMIN'), 
(2, 'PT'), 
(3, 'MEMBER');

INSERT IGNORE INTO `FitnessProject`.`users` (`id`, `fullname`, `email`, `password_hash`, `phone`, `role_id`) 
VALUES (1, 'Nguyễn Văn Admin', 'admin@fitness.com', '$2a$11$1Bjs3dENbnKx99Muw8XbTu4bHmgNIdZS491RU1URKMeOPR37XjmWi', '0123456789', 1);
INSERT IGNORE INTO `FitnessProject`.`users` (`id`, `fullname`, `email`, `password_hash`, `phone`, `role_id`)
VALUES (2, 'Huấn Luyện Viên', 'pt@fitness.com', '$2a$11$t9nhk9K0pu1kiGHvH9FaBOOcIo5fEKnEKE5gkh8pVue3UaOAhcHHq', '0123456789', 2);
INSERT IGNORE INTO `FitnessProject`.`users` (`id`, `fullname`, `email`, `password_hash`, `phone`, `role_id`) 
VALUES (3, 'Hội Viên', 'member@fitness.com', '$2a$11$xMG3qPdRx6zlnIXt4sUrv.iTSaunifiOyqeeJS/AZIZgQlXDsFrAm', '0123456789', 3);

INSERT IGNORE INTO `FitnessProject`.`foods` (`name`, `serving_size`, `unit`, `calories`, `protein`, `carbs`, `fat`) VALUES 
('Chicken Breast (Cooked)', '100', 'g', 165, 31.02, 0.00, 3.57),
('Brown Rice (Cooked)', '100', 'g', 112, 2.32, 23.51, 0.83),
('Broccoli (Raw)', '100', 'g', 34, 2.82, 6.64, 0.37),
('Whole Egg (Large)', '50', 'g', 72, 6.28, 0.36, 4.75),
('Egg White (Large)', '33', 'g', 17, 3.60, 0.24, 0.06),
('Salmon (Cooked)', '100', 'g', 206, 22.10, 0.00, 12.35),
('Almonds (Raw)', '30', 'g', 173, 6.36, 6.48, 14.94),
('Sweet Potato (Baked)', '100', 'g', 90, 2.01, 20.71, 0.15),
('Oats (Dry)', '100', 'g', 389, 16.89, 66.27, 6.90),
('Greek Yogurt (Non-fat)', '100', 'g', 59, 10.19, 3.60, 0.39),
('Spinach (Raw)', '100', 'g', 23, 2.86, 3.63, 0.39),
('Avocado (Raw)', '100', 'g', 160, 2.00, 8.53, 14.66),
('Banana', '100', 'g', 89, 1.09, 22.84, 0.33),
('Apple', '100', 'g', 52, 0.26, 13.81, 0.17),
('Peanut Butter (Smooth)', '32', 'g', 188, 8.03, 6.31, 16.06),
('Tuna (Canned in Water)', '100', 'g', 86, 19.44, 0.00, 0.96),
('Lentils (Cooked)', '100', 'g', 116, 9.02, 20.13, 0.38),
('Quinoa (Cooked)', '100', 'g', 120, 4.40, 21.30, 1.92),
('Olive Oil', '15', 'ml', 119, 0.00, 0.00, 13.50),
('Cottage Cheese (Low fat)', '100', 'g', 84, 11.12, 4.30, 2.25),
('Beef (Ground, 90% Lean)', '100', 'g', 176, 20.00, 0.00, 10.00),
('Turkey Breast (Cooked)', '100', 'g', 135, 30.13, 0.00, 0.74),
('Black Beans (Cooked)', '100', 'g', 132, 8.86, 23.71, 0.54),
('Chia Seeds', '28', 'g', 138, 4.68, 11.94, 8.71),
('Walnuts', '30', 'g', 196, 4.58, 4.11, 19.57),
('Blueberries (Raw)', '100', 'g', 57, 0.74, 14.49, 0.33),
('Strawberries (Raw)', '100', 'g', 32, 0.67, 7.68, 0.30),
('Carrots (Raw)', '100', 'g', 41, 0.93, 9.58, 0.24),
('Tomato (Raw)', '100', 'g', 18, 0.88, 3.89, 0.20),
('Cucumber (Raw)', '100', 'g', 15, 0.65, 3.63, 0.11),
('Whey Protein Isolate', '30', 'g', 110, 25.00, 1.00, 0.50);
-- Seed Muscle Groups
INSERT IGNORE INTO `FitnessProject`.`muscle_groups` (`id`, `name`, `description`) VALUES
(1, 'Chest', 'Pectoral muscles'),
(2, 'Back', 'Latissimus dorsi, rhomboids, trapezius, and lower back'),
(3, 'Legs', 'Quadriceps, hamstrings, glutes, and calves'),
(4, 'Shoulders', 'Deltoid muscles (anterior, lateral, posterior)'),
(5, 'Arms', 'Biceps, triceps, and forearms'),
(6, 'Core', 'Abdominals and obliques');

-- Seed Exercises
INSERT IGNORE INTO `FitnessProject`.`exercises` 
(`title`, `description`, `muscle_group_id`, `difficulty`, `equipment`, `duration`, `calories_burn_per_min`, `created_by`, `status`) VALUES
-- Chest (Muscle Group 1)
('Barbell Bench Press', 'Lie on a flat bench and press a barbell upwards.', 1, 'INTERMEDIATE', 'Barbell, Bench', 10, 5.0, 1, 'APPROVED'),
('Incline Dumbbell Press', 'Press dumbbells upwards on an incline bench.', 1, 'INTERMEDIATE', 'Dumbbells, Incline Bench', 10, 4.5, 1, 'APPROVED'),
('Push-ups', 'Standard bodyweight push-up targeting the chest.', 1, 'BEGINNER', 'Bodyweight', 5, 4.0, 1, 'APPROVED'),
('Cable Crossovers', 'Pull cables together in front of your chest.', 1, 'INTERMEDIATE', 'Cable Machine', 8, 4.0, 1, 'APPROVED'),
('Chest Flyes', 'Lie on a bench and perform flyes with dumbbells.', 1, 'BEGINNER', 'Dumbbells, Bench', 8, 3.5, 1, 'APPROVED'),

-- Back (Muscle Group 2)
('Deadlift', 'Lift a loaded barbell off the ground to the hips.', 2, 'ADVANCED', 'Barbell', 15, 6.5, 1, 'APPROVED'),
('Pull-ups', 'Pull your body up to a bar.', 2, 'INTERMEDIATE', 'Pull-up Bar', 5, 5.5, 1, 'APPROVED'),
('Barbell Rows', 'Bend over and pull a barbell to your lower chest.', 2, 'INTERMEDIATE', 'Barbell', 10, 5.0, 1, 'APPROVED'),
('Lat Pulldowns', 'Pull the bar down to your chest on a lat machine.', 2, 'BEGINNER', 'Lat Machine', 10, 4.0, 1, 'APPROVED'),
('Seated Cable Rows', 'Pull the cable handle towards your stomach while seated.', 2, 'BEGINNER', 'Cable Machine', 10, 4.0, 1, 'APPROVED'),

-- Legs (Muscle Group 3)
('Barbell Squats', 'Squat down with a barbell across your upper back.', 3, 'INTERMEDIATE', 'Barbell, Squat Rack', 15, 6.0, 1, 'APPROVED'),
('Leg Press', 'Press the platform away with your legs on the machine.', 3, 'BEGINNER', 'Leg Press Machine', 10, 5.0, 1, 'APPROVED'),
('Walking Lunges', 'Step forward into a lunge and repeat walking forward.', 3, 'BEGINNER', 'Bodyweight or Dumbbells', 10, 4.5, 1, 'APPROVED'),
('Leg Extensions', 'Extend your legs upwards on the extension machine.', 3, 'BEGINNER', 'Leg Extension Machine', 8, 3.0, 1, 'APPROVED'),
('Standing Calf Raises', 'Raise your heels off the ground standing.', 3, 'BEGINNER', 'Bodyweight or Machine', 5, 2.5, 1, 'APPROVED'),

-- Shoulders (Muscle Group 4)
('Overhead Press', 'Press a barbell or dumbbells overhead from the shoulders.', 4, 'INTERMEDIATE', 'Barbell or Dumbbells', 10, 4.5, 1, 'APPROVED'),
('Lateral Raises', 'Raise dumbbells out to your sides.', 4, 'BEGINNER', 'Dumbbells', 8, 3.0, 1, 'APPROVED'),
('Front Raises', 'Raise dumbbells straight out in front of you.', 4, 'BEGINNER', 'Dumbbells', 8, 3.0, 1, 'APPROVED'),
('Reverse Pec Deck', 'Pull the machine handles backwards targeting rear delts.', 4, 'BEGINNER', 'Pec Deck Machine', 8, 3.0, 1, 'APPROVED'),
('Arnold Press', 'Dumbbell press with a rotational movement.', 4, 'INTERMEDIATE', 'Dumbbells', 10, 4.0, 1, 'APPROVED'),

-- Arms (Muscle Group 5)
('Barbell Bicep Curls', 'Curl a barbell upwards towards your chest.', 5, 'BEGINNER', 'Barbell', 10, 3.0, 1, 'APPROVED'),
('Tricep Pushdowns', 'Push the cable attachment downwards.', 5, 'BEGINNER', 'Cable Machine', 10, 3.0, 1, 'APPROVED'),
('Hammer Curls', 'Curl dumbbells with a neutral grip.', 5, 'BEGINNER', 'Dumbbells', 8, 3.0, 1, 'APPROVED'),
('Skull Crushers', 'Lower an EZ bar to your forehead while lying down.', 5, 'INTERMEDIATE', 'EZ Bar, Bench', 10, 3.5, 1, 'APPROVED'),
('Concentration Curls', 'Curl a dumbbell while sitting, elbow resting on thigh.', 5, 'BEGINNER', 'Dumbbell', 8, 2.5, 1, 'APPROVED'),

-- Core (Muscle Group 6)
('Crunches', 'Basic abdominal crunch on the floor.', 6, 'BEGINNER', 'Bodyweight', 5, 3.5, 1, 'APPROVED'),
('Plank', 'Hold a push-up position resting on forearms.', 6, 'BEGINNER', 'Bodyweight', 5, 3.0, 1, 'APPROVED'),
('Russian Twists', 'Twist your torso side to side while seated, feet off floor.', 6, 'INTERMEDIATE', 'Bodyweight or Medicine Ball', 5, 4.0, 1, 'APPROVED'),
('Hanging Leg Raises', 'Hang from a bar and raise your legs up.', 6, 'ADVANCED', 'Pull-up Bar', 5, 4.5, 1, 'APPROVED'),
('Bicycle Crunches', 'Alternate bringing elbows to opposite knees.', 6, 'BEGINNER', 'Bodyweight', 5, 4.0, 1, 'APPROVED');


DROP TABLE IF EXISTS `EmailOTP`;

CREATE TABLE `EmailOTP` (
    `Id` CHAR(36) NOT NULL,
    `Email` VARCHAR(255) NOT NULL,
    `OTPCode` VARCHAR(10) NOT NULL,
    `Purpose` VARCHAR(50) NOT NULL,
    `ExpiredAt` DATETIME NOT NULL,
    `IsUsed` BIT(1) NOT NULL DEFAULT b'0',
    `AttemptCount` INT NOT NULL DEFAULT 0,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `IX_EmailOTP_Email` ON `EmailOTP` (`Email`);
CREATE INDEX `IX_EmailOTP_Purpose` ON `EmailOTP` (`Purpose`);
CREATE INDEX `IX_EmailOTP_ExpiredAt` ON `EmailOTP` (`ExpiredAt`);



-- -----------------------------------------------------
-- Table `FitnessProject`.`__EFMigrationsHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`__EFMigrationsHistory` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`__EFMigrationsHistory` (
  `migration_id` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `product_version` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`migration_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `FitnessProject`.`daily_nutrition_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FitnessProject`.`daily_nutrition_logs` ;

CREATE TABLE IF NOT EXISTS `FitnessProject`.`daily_nutrition_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `log_date` DATETIME(6) NOT NULL,
  `calories_target` INT NOT NULL,
  `protein_target_grams` DECIMAL(65,30) NOT NULL,
  `carbs_target_grams` DECIMAL(65,30) NOT NULL,
  `fat_target_grams` DECIMAL(65,30) NOT NULL,
  `water_target_glasses` INT NOT NULL,
  `calories_consumed` INT NOT NULL,
  `protein_consumed_grams` DECIMAL(65,30) NOT NULL,
  `carbs_consumed_grams` DECIMAL(65,30) NOT NULL,
  `fat_consumed_grams` DECIMAL(65,30) NOT NULL,
  `water_consumed_glasses` INT NOT NULL,
  `calories_burned` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IX_DailyNutritionLog_UserId_LogDate` (`user_id` ASC, `log_date` ASC) VISIBLE,
  CONSTRAINT `fk_daily_nutrition_logs_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `FitnessProject`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;